on:
  schedule:
    - cron: "0 17 * * *" # UTC
  workflow_dispatch:

jobs:
  turn_off:
    runs-on: ubuntu-latest
    steps:
      - name: Stop instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ secrets.INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
