on:
  schedule:
    - cron: "0 0 * * Mon-Fri" # UTC
  workflow_dispatch:

jobs:
  turn_on:
    runs-on: ubuntu-latest
    steps:
      - name: Start instance
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
